# Generated by Django 5.0.1 on 2024-01-08 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_center_slot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slot",
            name="username",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.user",
            ),
        ),
    ]
